### ISSUE TITLE
LICENSE situation

### ISSUE THREAD

**Issue by bollwyvl** [martinRenou/json-lsp#1]
Part of why I was less excited about this approach is there are _layers_ of nested licensing to be resolved here. 

It would be worth tracking down all of the upstream licenses before hitting the deploy button...

**Comment by martinRenou** [comment]
I went over all the dependencies that are listed in the `yarn.lock`, they are all MIT licensed so this seems fine :)

I am also less excited by this approach, and I might look at the `pygls` approach at some point (I need to get more confortable with the language server protocol). But this approach seems more reasonable/user-friendly than installing `vscode-json-languageserver-bin` in the right node_modules folder for jupyterlab-lsp to find, so it's already a good intermediate step IMO. What do you think?
